---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: kubeakshay111/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              value: "dan7jsw1s"
            - name: CLOUDINARY_KEY
              value: "636727655237421"
            - name: CLOUDINARY_SECRET
              value: "j7Awy4YbLZ5FhkuNSvktx37_SZM"
            - name: MAPBOX_TOKEN
              value: "sk.eyJ1IjoiYWtzaGF5a20xMTEiLCJhIjoiY20zeXczN3BvMXJ6MzJqczl1dHoyY3ZkYSJ9.Fc6ffFa-VJoe6HTutgyQ_A"
            - name: DB_URL
              value: "mongodb+srv://akshaymandre111:S2RYMQs7eeMhUXrJ@devops.zanr3.mongodb.net/?retryWrites=true&w=majority&appName=DevOps"
            - name: SECRET
              value: "DevOps"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
